name: mind_tracker
description: "A cross-platform mood and habit tracking app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts
  fl_chart: ^0.69.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  # Firebase (Optional)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  timezone: ^0.9.4
  
  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
